apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect4
  template:
    metadata:
      labels:
        app: connect4
    spec:
      containers:
        - name: connect4
          image: localhost:5000/connect4:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
   name: c4-entrypoint
   namespace: default
spec:
   type: NodePort
   selector:
      app: connect4  # Match the label defined in the Deployment
   ports:
      - port: 3000
        targetPort: 3000
        nodePort: 30002  # Make sure this port is within the allowed NodePort range